// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompareFields(arg1, arg2) {
  return window['go']['main']['App']['CompareFields'](arg1, arg2);
}

export function GetExcelHeaders(arg1) {
  return window['go']['main']['App']['GetExcelHeaders'](arg1);
}

export function GetTableColumns(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['GetTableColumns'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportExcel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['ImportExcel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}

export function TestDatabaseConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['TestDatabaseConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateProgress'](arg1, arg2);
}
