// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompareFields(arg1:Array<string>,arg2:Array<string>):Promise<Record<string, any>>;

export function GetExcelHeaders(arg1:string):Promise<Array<string>>;

export function GetTableColumns(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ImportExcel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string):Promise<string>;

export function LoadConfig():Promise<main.DBConfig>;

export function SaveConfig(arg1:main.DBConfig):Promise<string>;

export function SelectExcelFile():Promise<string>;

export function TestDatabaseConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;

export function UpdateProgress(arg1:number,arg2:string):Promise<void>;
